### ISSUE TITLE
document built-in xtriggers

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-doc#106]
Follow-on from https://github.com/cylc/cylc-flow/pull/3457
Attempt after: https://github.com/cylc/cylc-flow/issues/3456

Auto-document the Cylc Flow built-in Xtriggers from their doc strings.

**Comment by hjoliver** [comment]
Also, we need to better document how users call built-in xtrigger functions.  REF https://cylc.discourse.group/t/xtrigger-suite-state-function-usage/219
