### ISSUE TITLE
Explain the security model for cylc 8

### ISSUE THREAD

**Issue by jarich** [cylc/cylc-doc#113]
Explain the architecture, security principles and processes for cylc 8.

Include:
- [x] current architecture
- [ ] JupyterHub security page [link](https://cylc.github.io/cylc-doc/stable/html/reference/architecture/ui-server.html#multi-user-mode) and security model
- [ ] Link to JupyterHub's authentication plugins
- [x] [Hub - UI Server](https://cylc.github.io/cylc-doc/stable/html/reference/architecture/data-flow.html)
- [x] [UI server to workflows to jobs](https://cylc.github.io/cylc-doc/stable/html/reference/architecture/data-flow.html)
- [x] [ZeroMQ security section](https://github.com/cylc/cylc-doc/pull/285/)
- [x] [certificates](https://github.com/cylc/cylc-doc/blob/609246426ef4b784924f092c80d1ba6d79b56e44/src/user-guide/running-workflows/authentication-files.rst)
- [x] [web sockets & HTTPS connections](https://cylc.github.io/cylc-doc/stable/html/reference/architecture/data-flow.html)

**Comment by hjoliver** [comment]
(From Riot post by @kinow )

> Will check if they have updated their docs with this info, but Min RK (main maintainer of jupyterhub/pyzmq/etc) posted some months ago on their discourse details about the cookies used in jupyterhub: https://discourse.jupyter.org/t/how-to-force-re-login-for-users/1998/6
>
> It shows both which cookies are created, by which parts of the system, when they are created, how they are secured (bound to paths... but there's also https/secure/and other flags for browsers).
>
> (Note that there is also a connection from hub to UI Server via http, to validate the oauth authentication. Handled by the same JupyterHub class used with notebooks for auth: https://github.com/cylc/cylc-uiserver/blob/5637c1a40f94123c47cc1e5c33704102a75ffaf4/cylc/uiserver/main.py#L163)

**Comment by oliver-sanders** [comment]
(On hold until https://github.com/cylc/cylc-uiserver/issues/219 and https://github.com/cylc/cylc-uiserver/pull/204 are completed)

**Comment by hjoliver** [comment]
See also https://github.com/cylc/cylc-doc/pull/116#pullrequestreview-757001853

**Comment by oliver-sanders** [comment]
See also https://github.com/cylc/cylc-doc/pull/285
