### ISSUE TITLE
What mixed curly brackes and square brackets mean under the task messaging?

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-doc#118]
This week I was looking at Cylc 7 source code, and reading again the CUG looking for some settings when I noticed some sections had "15.2.2.1. [retry interval]{[task messaging] -> retry interval".

Is the **[retry interval]{[task messaging]** mixing brackets intentional? Does it mean anything in special, like child task of something, or required, etc?

![image](https://user-images.githubusercontent.com/304786/76275574-7d291300-62e8-11ea-93eb-d75f72d92c28.png)

Link: https://cylc.github.io/doc/built-sphinx-single/index.html#retry-interval-task-messaging-retry-interval

**Comment by oliver-sanders** [comment]
I expect those are left over from when the documentation was converted from Latex.

**Comment by oliver-sanders** [comment]
Fixed by the auto-documentation of the config tree.
