### ISSUE TITLE
Rename section title from Ssh Task Messaging to "SSH" Task Messaging

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-doc#120]
Only place in the docs that uses Ssh instead of SSH. Should it be SSH or is there a reason for keeping it Ssh @oliver-sanders ? Maybe a sphinx requirement for heading titles?

![image](https://user-images.githubusercontent.com/304786/78614857-ebe79500-78c3-11ea-9ba8-672149aa47e7.png)

**Comment by oliver-sanders** [comment]
I guess this should be changed.

We will need to re-write this anyway.
