### ISSUE TITLE
minor doc change: use of # in shell transcript lines

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-doc#14]
Evidently some new users might misinterpret `#` as a shell prompt rather than a comment, in some contexts - #2695 .  It should be easy enough to make these completely unambiguous.

**Comment by oliver-sanders** [comment]
If we move to using `console` as the highlight language and place comments after the `$PS1` comments get greyed out avoiding confusion e.g:

```console
$ ls
foo
$ # comment
$ echo hello
hello
```

**Comment by matthewrmshin** [comment]
Yes, "#" is the default prompt for the "root" user, as opposed to "$" for normal users.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by oliver-sanders** [comment]
Code examples how use PS1=$
