### ISSUE TITLE
Document new task states

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-doc#163]
Reference: https://cylc.github.io/cylc-admin/proposal-state-names.html

* [x] Update task state list.
* [x] Document task state modifiers (e.g. held)
* [x] Check "EventHandling" section for references to dead states. There is a state list.
* [x] https://github.com/cylc/cylc-doc/issues/162

**Comment by oliver-sanders** [comment]
Currently documented in the "running workflows" section.

**Comment by wxtim** [comment]
- [ ] Check "EventHandling" section for references to dead states. There is a state list.

**Comment by MetRonnie** [comment]
> Check "EventHandling" section for references to dead states. There is a state list.

Ticked off by #316?

**Comment by hjoliver** [comment]
Taking "document task state modifiers" as done via the UI quick guide page, at least. We may need to add more in the user guide, but no biggie.
