### ISSUE TITLE
7-to-8 migration guide

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-doc#170]
Check list of items that will need to be noted (ADD TO THIS LIST AS NEEDED)
- [x] `suite.rc` -> `flow.cylc`
- [x] restart from Cylc 7 DB not supported
- [x] new run semantics (`cylc play` etc.; and the `run1, run2, ...` sub-dirs
- [x] new scheduling section syntax
- [x] deprecated config items: recommend upgrading them
- [x] task state name translation (was 13 states, now 8)
- [x] named state checkpoints gone 
   - https://github.com/cylc/cylc-flow/issues/3891
   - recommend use of reflow-based warm start: https://github.com/cylc/cylc-flow/issues/3864#issuecomment-708699402
- [x] platforms concept explainer

Transferred from @oliver-sanders comment below:

Suggested topics:

* [x] cylc install (w/ note on `[install]source dirs` & run numbs/names "safe run semantics")
* [x] platforms
* [x] play / pause / stop (w/ note about hold/release)
* [x] reflow
* [x] remote installation (w/ note on `[scheduler]install` for people who used to use `rose suite-run`)
* [x] runahead limit changes (w/ recommendation to use queues where possible)
* [x] symlink dirs (for people who used the Rose `root dir` config to do this, note per-workflow conf is no longer possible) https://github.com/cylc/cylc-doc/pull/369
* [x] suicide triggers #241
* [x] suicide triggers update post possible SoD changes.
* [x] rose suite-run to cylc install migration (now remembers options)
* [x] rose stem (now provided by cylc install)
* [x] `allow implicit tasks` (note: doesn't affect Rose2019 users) (note: add link to migration page in warning message). https://github.com/cylc/cylc-doc/pull/304 https://github.com/cylc/cylc-flow/pull/4572

**Comment by oliver-sanders** [comment]
Added a section for documenting Cylc 8 changes in https://github.com/cylc/cylc-doc/pull/241, just need to populate it!

Suggest the following format:

1. An admonition at the top of the page quickly conveying whether this is something the reader should delve into.
2. 1-2 line description of functionality if necessary.
3. Quick description of the change.
4. Example diff if required.

Example - https://github.com/cylc/cylc-doc/pull/241/files#diff-705a4752ecedd74e974b38897f45a8313a1042872eb7ead9056dd54080a37b61

These sections should be short, avoid documenting the actual feature here, just convey the change and link through to the main documentation.

**Comment by oliver-sanders** [comment]
Suggested topics:

* [ ] cylc install (w/ note on `[install]source dirs` & run numbs/names "safe run semantics")
* [ ] monitor -> tui
* [ ] platforms
* [ ] play / pause / stop (w/ note about hold/release)
* [ ] reflow
* [ ] remote installation (w/ note on `[scheduler]install`)
* [ ] runahead limit changes (w/ recommendation to use queues where possible)
* [ ] symlink dirs
* [x] suicide triggers #241

**Comment by wxtim** [comment]
I'm going to have a go at writing sections on Cylc install / reinstall, and subsequently stem.

**Comment by MetRonnie** [comment]
> `suite.rc` -> `flow.cylc`

I would say this is covered by https://cylc.github.io/cylc-doc/nightly/html/7-to-8/summary.html#admonition-0

> restart from Cylc 7 DB not supported

I think that could go in https://cylc.github.io/cylc-doc/nightly/html/7-to-8/summary.html#backward-compatibility

> deprecated config items: recommend upgrading them

Covered by https://cylc.github.io/cylc-doc/nightly/html/7-to-8/summary.html#admonition-1

**Comment by hjoliver** [comment]
Oops, I had forgotten about this issue.  Some of the items done already, will review.

**Comment by hjoliver** [comment]
> >  restart from Cylc 7 DB not supported
> 
> I think that could go in https://cylc.github.io/cylc-doc/nightly/html/7-to-8/summary.html#backward-compatibility

Done - added to #310

**Comment by hjoliver** [comment]
Checked off *named checkpoints are gone* - noted in the 7-8 Major Changes section.

**Comment by hjoliver** [comment]
Checked off *remote installation*. Covered in 7-8 Major Changes, with links that follow through to the relevant config.

**Comment by hjoliver** [comment]
All done. :tada:
