### ISSUE TITLE
Fix "ICP relative to current time" in CUG suite.rc reference.

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-doc#19]
![Screenshot from 2019-06-05 23-53-40](https://user-images.githubusercontent.com/2362137/58954537-90ed9900-87ed-11e9-8f6d-e22a8903a7d6.png)

The heading shown should be just a minor doc heading, but is formatted as if `[initial cycle point]` is a config section and "initial cycle point relative to current time" is a config item.

**Comment by hjoliver** [comment]
While we're at it, the meaning of the `T-05` style syntax should be explained more clearly. This:
```
initial cycle point = next(T-05; T-10)
```
means *the next (5 min past the hour, or 10 min past the hour), whatever the current hour*.  So if current time is 16:01 the ICP will be 16:05; if current time is 16:07 the ICP will be 16:10; and if current time is 16:13 the ICP will be 17:05.

**Comment by oliver-sanders** [comment]
I thought we had an issue for this somewhere...

BTW: We kinda documented the meaning of the hyphen in the Cylc tutorial in the Rose documentation:

http://metomi.github.io/rose/doc/html/tutorial/cylc/scheduling/datetime-cycling.html#inferred-recurrence

**Comment by oliver-sanders** [comment]
Formatting issue fixed by auto-documentation of config tree.

Opening a new issue to better explain the T-XX syntax in the previous/next sections - https://github.com/cylc/cylc-doc/issues/367.
