### ISSUE TITLE
overflowing diagrams

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-doc#209]
Some of the graphviz generated diagrams are overflowing:

![overflow](https://user-images.githubusercontent.com/16705946/111145272-f99ba500-857f-11eb-927d-82b63a1b9706.png)

* I think this may be a change in Sphinx? (I can't imagine it is a change in graphviz?).
* I think this effects graphs which have explicitly set the graphviz `size` attribute.

Find out what's going on. Can we remove the `size` attr, otherwise try to find sensible new values (make sure they work when you resize the page [at least as much as can be expected]).

**Comment by MetRonnie** [comment]
I have noticed when building the docs locally, the diagrams do not overflow.

Here is a comparison of some relevant-looking extensions:

| Package                        | Local  | GH Actions         |
| ------------------------------ | ------ | ------------------ |
| hieroglyph                     | 2.1.0  | 2.1.0              |
| imagesize                      | 1.2.0  | 1.2.0              |
| pygraphviz                     | 1.5    | **1.7**            |
| Sphinx                         | 3.5.4  | 3.5.4              |
| sphinx-rtd-theme               | 0.5.0  | **0.5.2**          |
| sphinxcontrib-applehelp        | 1.0.2  | 1.0.2              |
| sphinxcontrib-devhelp          | 1.0.2  | 1.0.2              |
| sphinxcontrib-htmlhelp         | 1.0.3  | 1.0.3              |
| sphinxcontrib-jsmath           | 1.0.1  | 1.0.1              |
| sphinxcontrib-qthelp           | 1.0.3  | 1.0.3              |
| sphinxcontrib-serializinghtml  | 1.1.4  | 1.1.4              |
| sphinxcontrib-svg2pdfconverter | 1.0.1  | **1.1.1**          |
| graphviz                       | 2.38.0 | **2.42.2-3build2** |

**Comment by oliver-sanders** [comment]
Hmmm, my money is on `sphinx-rtd-theme`.

**Comment by MetRonnie** [comment]
I've narrowed the issue down to being the result of the main `g` element of the generated svg receiving a
```
transform="scale(1.34 1.34) rotate(0) translate(4 477.7)"
```
attribute with a `scale` that is 1.79x bigger than before.

This seems to be fixed by setting the OS for the GH Actions workflows to `ubuntu-18.04` which [has `graphviz 2.40.1-2` in apt](https://packages.ubuntu.com/search?keywords=graphviz&searchon=names&suite=bionic&section=all)

**Comment by MetRonnie** [comment]
This looks like the bug report for the issue - https://gitlab.com/graphviz/graphviz/-/issues/1855

**Comment by oliver-sanders** [comment]
Ooh, good spot.

**Comment by oliver-sanders** [comment]
Opened a follow on to revert the OS change when Graphviz is fixed https://github.com/cylc/cylc-doc/issues/247
