### ISSUE TITLE
split up the running suites section

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-doc#211]
The "User Guide > Running Suites" section is all written in a single file.

The "User Guide > Writing Suites" section has been broken down into a tree of the same name with a landing page with a contents listing. We should do the same for the "Running Suites" section.

> **Tip**: When moving files down a level remember to add `../` to all sources (images, code files, etc).

**Comment by wxtim** [comment]
I've started doing this is a fairly mechanical way, but I've become concerned that this document should be reviewed _before_ being chunked to ensure that it forms a logical Cylc 8 whole.

Happy to have a go at this, but won't be able to do all of it without input.

What do you think @oliver-sanders

**Comment by oliver-sanders** [comment]
This has had a first pass, however, still needs work.

Taking a quick look through a lot of the content really belongs in writing workflows:

* Runahead Limiting
* Limiting Activity With Internal Queues
* Automatic Task Retry On Failure
* Task Event Handling
* The Meaning And Use Of Initial Cycle Point
* Triggering Off Of Tasks In Other Workflows

Just lifting these sections out and integrating them with the other docs would be a good start.

I think the running workflows section should be all about pure runtime stuff i.e. `cylc play`, `cylc reload`, `cylc broadcast`, run modes, the files that are created task messaging, etc.

These sections need mangling:

* Alternate Run Directories
  * This is about symlink dirs, alternate run dirs are gone.
* Task States Explained
  * This is out of date, raise a separate issue to fix this.
  * I think this is more of a writing workflows topic?
* Disaster Recovery
  * Still valid, raise a separate issue?

These sections need deleting:

* Manual Task Triggering and Edit-Run
  * Edit run is no more.

The remaining bits could probably be organised along the lines of:

* Play (start, restart)
* Changing the configuration (broadcast, reload)
* Workflow files (contact, logs, database)
* Task comms (ssh, ssh+tcp, tcp, polling, tracking jobs)
* Run modes (dummy, simulation, live) TODO fact check
* Misc (auto-stop-restart, sub-workflows)

**Comment by wxtim** [comment]
> Task States Explained
>
>    This is out of date, raise a separate issue to fix this.
>    I think this is more of a writing workflows topic?

#163

**Comment by wxtim** [comment]
#### Done
- [x] created running-workflows dir; changed links
- [x] removed edit-run section
- [x] Moved Runahead Limiting and Queues into writing-workflows/scheduling
- [x] Deleted Task states section

#### Deliberately not addressed
- Task states work described by #163 
-
