### ISSUE TITLE
tutorial: re-write for cylc8

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-doc#218]
The tutorial will need upgrading and partially re-writing for Cylc8.

**Comment by wxtim** [comment]
#### Dependencies on Cylc Graph:
- [ ] `src/tutorial/scheduling/graphing.rst

**Comment by oliver-sanders** [comment]
I think so, can introduce the `cylc-run` dir and `cylc install` at the same time, no need to get users into the bad habit of writing directly in `cylc-run`.

**Comment by oliver-sanders** [comment]
I've put the blocked label on this as a reminder of some of the major changes we should wait for before starting in earnest:

* [ ] The new optional outputs syntax (which will change the graph syntax).
* [ ] runN inference
  * https://github.com/cylc/cylc-flow/pull/4285
  * Changes the CLI.
* [ ] The universal ID
   * https://github.com/cylc/cylc-flow/issues/3592
  * Changes the CLI and some terminology.
* [x] `cylc graph` resurrection.

**Comment by wxtim** [comment]
I've jumped the gun again. I'm going to put what I've done this morning up for review, since I think it's worth having.

**Comment by oliver-sanders** [comment]
Two points from a rose issue:

* [ ] Provide some sample data an instructions to use it so the tutorial suite can be run of-line.
* [ ] Rainfall data can wrap in the y dimension.
