### ISSUE TITLE
Isodatetime format explanation image messed up

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-doc#243]
https://cylc.github.io/cylc-doc/8.0b0/html/tutorial/scheduling/datetime-cycling.html#iso8601-date-times

Strange because it's a PNG. And not messed up in the 8.0a2 version of the docs.

<img src="https://cylc.github.io/cylc-doc/8.0b0/html/_images/iso8601-dates.png"/>

**Comment by oliver-sanders** [comment]
Fixed again on nightly, related to https://github.com/cylc/cylc-doc/issues/209?

<img width="788" alt="Screenshot 2021-06-08 at 15 39 06" src="https://user-images.githubusercontent.com/16705946/121205566-adef5380-c86f-11eb-94e2-41856067a8dc.png">

**Comment by MetRonnie** [comment]
Is it a font issue?

Also, why is becoming a PNG when it's an SVG to begin with? `src/tutorial/img/iso8601-dates.svg`

**Comment by oliver-sanders** [comment]
> Also, why is becoming a PNG when it's an SVG to begin with

Is a good question.

The graphviz graphs come out as SVGs (there's a switch in conf.py to make that happen) why is this converted to PNG?

**Comment by oliver-sanders** [comment]
Another messed up image on the running suites page - https://cylc.github.io/cylc-doc/latest/html/user-guide/running-suites.html

![image](https://user-images.githubusercontent.com/16705946/125614866-bb1b5f93-eb53-4c3f-94cc-611946bad505.png)

**Comment by oliver-sanders** [comment]
@MetRonnie can we close this?

**Comment by MetRonnie** [comment]
I think we should redeploy the affected versions to fix it first. I can have a go at that this afternoon

**Comment by oliver-sanders** [comment]
Not really necessary, we will release a new beta soon, can delete the old beta docs when we do it.

**Comment by MetRonnie** [comment]
I got confused between this issue and #209 for a moment. I guess this was fixed by rolling back Ubuntu to 18 because one of the apt dependencies changed behaviour, but we didn't figure out which one
