### ISSUE TITLE
Document Symlink Dirs

### ISSUE THREAD

**Issue by wxtim** [cylc/cylc-doc#267]
Replace the 'Alternate Run Dirs' Section in "Running Workflows with a new document."

**Comment by MetRonnie** [comment]
There is mention of the symlink dirs in:
- the user guide for `cylc install`: https://cylc.github.io/cylc-doc/8.0b3/html/user-guide/installing-workflows.html#symlinking-of-directories
- the migration guide: https://cylc.github.io/cylc-doc/8.0b3/html/7-to-8/summary.html#symlink-dirs

However, I think it could do with a more prominent or earlier mention in the user guide for `cylc install`, 
perhaps before the [Named Runs section](https://cylc.github.io/cylc-doc/8.0b3/html/user-guide/installing-workflows.html#named-runs). It could explain that these are useful for offloading large data onto other drives etc.
