### ISSUE TITLE
Post-packaging update to installation instructions

### ISSUE THREAD

**Issue by sadielbartholomew** [cylc/cylc-doc#27]
The 'Installation' documentation section (quick link [here](https://cylc.github.io/doc/built-sphinx/installation.html)) will need updating to reflect the state of Cylc 8, which has diverged greatly to Cylc 7 with respect to installation approaches & requirements.

The update should at least update the now-outdated information on:

* revised requirements for other packages: Python 3.X range, further package dependencies, bundled packages (if any); 
* new installation method via PyPI (& conda, if possible at the time of closing) & ``setup.py``;
* new information required so users can understand how to inter-connect various Cylc 8 components, now in separate repositories.

**Comment by oliver-sanders** [comment]
Done.
