### ISSUE TITLE
Document reload and re-install 

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-doc#272]
Something like this (from answer to a question on cylc-general Element chat):

> There are two ways to reload a workflow definition after making changes:
>
>  1.  modify the installed `~/cylc-run/john/run1/flow.cylc` then do `cylc reload john/run1` (not recommended, except perhaps for temporary changes)
>  2. modify the source `~/cylc-src/john/flow.cylc`, then re-install it with `cylc reinstall john/run1`, then do `cylc reload john/run1`
> 
> Note that `cylc reinstall` "re-installs" from source to the existing workflow run directory, it doesn't create a new install for a new run from scratch like `cylc install` does.
>
> If you just modified the source and did not do `cylc re-install <run-name>` then `cylc reload` won't pick up any changes.
(i.e. cylc reload looks at the live (/installed) workflow definition, not the source one)
>
> If you did either 1. or 2. above but made an error in the `flow.cylc` file, the scheduler log will report an error on trying to reload it, and the reload will have no effect.
>
> Finally, if you added a new task via either 1. or 2. above, should you see it immediately in `cylc tui` or cylc-ui? Only when or if the new task appears in the "n=1 graph window" relative to active tasks. i.e. when/if it is one graph edge away from active tasks.
>
> Example, if my running graph is `foo => bar` and I reload after changing it to `foo => bar => baz`, then:
> 
> 1.    if I reload when `foo` is running, `baz` won't appear (at n=1) until `bar` is active (and it will run after `bar` succeeds
> 2.    if I reload when `bar` is running, the scheduler will log that `bar` is already active with pre-reload settings (which includes its output triggers) so in this case `baz` will not appear, and will not run. (Except: if this is a cycling workflow future instances of `bar` will run with the new settings, and `baz` will run after those).

**Comment by oliver-sanders** [comment]
See this TODO:

https://github.com/cylc/cylc-flow/blob/ed19b4b5e574f1c7170e77722a939f6d2dfe8d5c/cylc/flow/task_pool.py#L767-L781

**Comment by MetRonnie** [comment]
Is this adequately addressed by https://cylc.github.io/cylc-doc/nightly/html/user-guide/running-workflows/scheduler-start-up.html?highlight=reload#reloading-the-workflow-configuration-at-runtime?

**Comment by hjoliver** [comment]
> Is this adequately addressed by https://cylc.github.io/cylc-doc/nightly/html/user-guide/running-workflows/scheduler-start-up.html?highlight=reload#reloading-the-workflow-configuration-at-runtime?

Yes :+1:

**Comment by hjoliver** [comment]
> See this TODO:
> 
> https://github.com/cylc/cylc-flow/blob/ed19b4b5e574f1c7170e77722a939f6d2dfe8d5c/cylc/flow/task_pool.py#L767-L781

I've removed this obsolete TODO from the docstring via a single-commit hot-fix to cylc-flow master.
