### ISSUE TITLE
whats new page

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-doc#314]
We should include the changelog(s) in the docs, note Sphinx *can* handle markdown if needed.

We could do with a list of major changes for each Cylc meta-package release, could do that in the changelog files or, alternatively collate the major changes from the different repos into a page here.

> **Note:** We *can* document changelog files (Sphinx does support Markdown). It would be nice to document these (changelogs will then appear in search results).

> **Note:** We currently have a "major changes" page detailing Cylc < 8 versions.

Question:

* Are we happy to compile the major changes for a release here or is there a better place?
* Should we document maintenance releases or just minor releases?

**Comment by oliver-sanders** [comment]
Suggest creating a "what's new" or "changes" page with a hand-crafted summary of major changes across the projects similar to the [Python highlights page](https://docs.python.org/3/whatsnew/3.10.html#summary-release-highlights).

Then incorporating the changelog files from the individual projects.

**Comment by hjoliver** [comment]
Yes, I like that approach. 

If no one objects, we can review the question label at the meeting, and move on with this.

**Comment by wxtim** [comment]
I agree with this approach - I think that we need to keep editorial control of the top level headlines, but if it's simple enough we can also include all changelogs as well.

**Comment by hjoliver** [comment]
(whole project/ multi-repo)

**Comment by oliver-sanders** [comment]
Discussed at developers meeting.
