### ISSUE TITLE
Should CONTROL permissions imply READ?

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-doc#322]
We can grant CONTROL and READ permissions separately, but the former does not automatically imply the latter.

From @datamel :

>  The reason we are keeping them separate is due to negations. If you did !CONTROL, that should not remove read access and so, by logic CONTROL should not add read access. I think having the addition doing something different to the negation would be unexpected for users. I appreciate that we could go either way on this one though, maybe worth a discussion at VC this week

**Comment by oliver-sanders** [comment]
Now a docs issue.

**Comment by hjoliver** [comment]
Updated with a hot fix to master:

>  .. note::
>  
 >    Granting CONTROL access does not automatically grant READ access.
