### ISSUE TITLE
Document "when the task pool matters".

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-doc#34]
(Ref recent discussion with Alan on Riot.im)

Users (unfortunately) need to understand the server "task pool" and how it evolves, in certain situations:
- consequences of spawn-on-submit:
  - (implicit dependence `foo[-P1]:submit => foo`)
   - successive instances of a task can run concurrently, but not out of order
  - suites can stall due to un-spawned successors of tasks waiting downstream of a failed task (the next instance of the failed task itself will be spawned)

- dynamic manipulation of workflow structure:
  - task-targeting commands and suicide triggers operate on task proxies currently present in the pool, not on the abstract workflow graph.

Spawn-on-demand (Cylc 9?) should fix these deficiencies.  In the meantime, `spawn to max active cycle points` may be a good workaround for many suites.

**Comment by oliver-sanders** [comment]
Closed by SoD
