### ISSUE TITLE
Cylc UI Server: Document Hub spawners

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-doc#36]
- [ ] SSH Spawner - https://github.com/cylc/cylc-uiserver/issues/46
- [x] Local Process Spawner (I think that's done as that's the one we have per default in cylc-uiserver?)
- [ ] Batch Spawner - https://github.com/cylc/cylc-uiserver/issues/15

**Comment by oliver-sanders** [comment]
We now point users at the Jupyter Hub docs which covers this topic in more detail than we would be able to.
