### ISSUE TITLE
Missing dependency on ImageMagick

### ISSUE THREAD

**Issue by hiker** [cylc/cylc-doc#375]
Hi,
we just tested the 8.0b3 release, and while starting on the tutorial, visualising the graph (one of the first things in the tutorial: https://cylc.github.io/cylc-doc/8.0b3/html/tutorial/scheduling/graphing.html#admonition-4) did not work, no graph was displayed. It turns out that this machine did not have ImageMagick installed (which includes 'display`, which cylc apparently uses).

We did not see this dependency mentioned in the documentation. It would be great if this could be added!

**Comment by hiker** [comment]
I just realised (https://cylc.github.io/cylc-doc/8.0b3/html/installation.html#non-python-requirements):
```
These dependencies are not installed by Conda or pip:

bash

GNU coreutils

mail (optional: for automated email functionality)

These dependencies are installed by Conda but not by pip (you can use npm):
```
Conda both does not install and does install the dependencies :)

**Comment by oliver-sanders** [comment]
Curious, Cylc doesn't use the `display` command or any ImageMagick interfaces. ImageMagick might be a transient dependency of another package but I don't think its a direct dependency of Cylc itself.

Could you provide a bit of debugging info to help identify the problem. How did you install graphviz?

Note: we have an optional dependency on `pillow` which is used to display the graph in a window if installed (otherwise it prints the path to the file).

(FYI on the Conda dependencies, we could add Bash and Coreutils as dependencies of Cylc but these would replace the system installed versions within the Cylc environment which might not be desirable so they are omitted for now, we'll try to erode these system dependencies in due course).

**Comment by hiker** [comment]
Sorry for the delay, too busy.
``` 
0 S joerg     4445     8  0  80   0 -   654 do_wai 23:28 pts/5    00:00:00 /bin/sh -c im=$(cat);display $im; rm -f $im
0 S joerg     4447  4445  0  80   0 - 25478 x64_sy 23:28 pts/5    00:00:00 display /tmp/tmp7523xstk.PNG
```
This is what is running when I execute `cylc graph` (9 is init on my WSL2). Pillow is install via pip, thought I don't know as a result of which other package (I am reasonable certain I did not explicitly install it). Graphviz is installed via pip as well (and was a dependency of PSyclone, so it was installed).

My team member who tried to run the tutorial did not have ImageMagick installed, and installed cylc following your installation guide using conda (I used pip).

And I just did a clean install on an was node:
```
pip3 install --user  cylc-flow
sudo yum install graphviz    # Otherwise cylc graph displays that graphviz must be installed
```
This indeed display a path in /tmp with the image data. If I then do:
```
pip3 install --user Pillow
```
I indeed get the behaviour reported: `cylc graph` does not print the path anymore, but neither is a image displayed. If I installed ImageMagic, it works.

So it looks that if Pillow is installed, but not ImageMagic, the `cylc graph` command does neither display the graph, nor does it show the location of the file - it just silently finishes.

**Comment by hiker** [comment]
While I am happy with the solution, I double-checked, and I don't have a `display` command available at all (after removing ImageMagick), and indeed python's `shutils.which("display")` returns False. Being curious to understand this, I dug a bit deeper:

PIL(low) does not find any viewer. ImageShow.py provides a stand-alone `show` function, which will return if any viewer was able to display the file. And while the show method of the Image class uses this show function, the method does not return a return value, it will always return None. So, if you would use the `show` function from ImageShow directly, you could test for the return value to decide what to do (e.g. a more explicit message in like: "could not find a viewer like display, eog, xv, ...").This of course is annoying to maintain, since this list might change in pillow, and will depend on OS, ...

But I totally agree, from a user's point of view the effect is the same as the patch, so I am happy with the solution, and that I now know that my system is not broken :)
