### ISSUE TITLE
728: include/exclude at start up

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-doc#389]
The Cylc 7 `include at startup` and `exclude at startup` configurations have been removed with no failsafe deprecation logic.

We should add an entry to the major changes section of the migration guide for them.

Will need to read up about the old configs and try them out as I think they were a bit strange from memory. Should try to offer contemporary solutions for implementing them.

**Comment by MetRonnie** [comment]
I can't find any reference to them in the 7.9.3 docs https://cylc.github.io/cylc-doc/7.9.3/singlehtml/index.html

**Comment by oliver-sanders** [comment]
https://cylc.github.io/cylc-doc/7.8.8/html/appendices/suiterc-config-ref.html#scheduling-special-tasks-exclude-at-start-up
