### ISSUE TITLE
xtriggers: undocumented restricted nature of results dict

### ISSUE THREAD

**Issue by sadielbartholomew** [cylc/cylc-doc#41]
The keys in the ``results`` dictionary returned in the satisfied signature ``(True, results)`` from a external trigger function become appended to the xtrigger name to form an environment variable identifier, which places many restrictions on these keys that are undocumented under the 'Custom Trigger Functions' section (only perhaps alluded to in the section ['Built-in Suite State Triggers'](https://cylc.github.io/doc/built-sphinx-single/index.html#built-in-suite-state-triggers) docs section which is referenced there). All that is stated there now is that "``results`` is *an arbitrary* dictionary of information to be passed to dependent tasks"

If keys that do not conform are used, then all tasks depending on the xtrigger will fail, due to an error in exporting the variables named from the keys that get passed along. The ``job.err`` for the downstream tasks will show, e.g. if a key ``-2`` was used:

```bash
... 01/job: line 34: export: `breakable_xtrigger_-2': not a valid identifier
2019-07-23T21:53:21+01:00 CRITICAL - failed/EXIT
```

Furthermore, there is no explicit mention that the ``results`` dict cannot be nested, to form some more complex data structure to pass through, which users could assume (I did so myself). Given the above, & after investigation, it does seem that ``results`` must be flat, else some very strange suite behaviour followed by suite shutdown (see cylc/cylc-flow#3237) results, so this should also be explicitly documented.

**So, in short, the following should be clearly documented, under the 'Custom Trigger Functions' &/or 'Current Limitations' sections, ideally with an indication of the symptoms of invalid keys to help users debug:**:

* ``results`` dict keys must be only contain characters that are valid within an environment variable (no easy standard to find but [this thread suggests](https://stackoverflow.com/questions/2821043/allowed-characters-in-linux-environment-variable-names) being all alphanumeric or underscores only as tested below);
* the ``results`` dict must be flat.

### Illustrative examples:

Use this custom trigger function in a basic suite & change the toggle variable systematically to observe the final task state of some trivial dependent tasks for each ``results`` case, where the dict value indicates whether the above problem emerges or not:

```python
def breakable_script(toggle):
    if toggle == "singlequote":
        return (True, {'AMIBROKEN': 'no'})
    elif toggle == "underscore":
        return (True, {"Am_I_broken": "no"})
    elif toggle == "plainnumeric":
        return (True, {2: "no"})
    elif toggle == "space":
        return (True, {"Am I broken": "yes"})  # triggered tasks fail
    elif toggle == "dash":
        return (True, {"Am-I-broken": "yes"})  # triggered tasks fail
    elif toggle == "signednumeric":
        return (True, {-2: "yes"})  # broken: triggered tasks fail
    elif toggle == "comma":
        return (True, {"Am,I,broken": "yes"})  # triggered tasks fail
    elif toggle == "dot":
        return (True, {"Am.I.broken": "yes"})  # triggered tasks fail
    elif toggle == "float":
        return (True, {2.5: "yes"})  # broken: triggered tasks fail
    elif toggle == "slash":
        return (True, {"Am/I/broken": "yes"})  # triggered tasks fail
    elif toggle == "nested":
        res = {"dictA": {"keyA": "valueA"},
               "dictB": {"keyB": "valueB"}}
        return (True, res)  # this one is broken in a much funkier way!
    else:
        return True, {}
```

**Comment by sadielbartholomew** [comment]
@hjoliver, I am happy to tackle this to document the restrictions, but I don't want to make any assumptions so whenever you get time (no problem if that isn't for a long while) could you just let me know if the above restrictions are correct? I've deduced them from investigations on minimla suites, but I could have misunderstood something. Thanks.

**Comment by hjoliver** [comment]
Thanks @sadielbartholomew (and apologies for missing this in the docs). 

Yes, the purpose of the results dictionary is to allow passing information (about the satisfied trigger) to dependent task job environments.  The information passed is arbitrary, but its format has to be compatible with environment variables (in the ways you noted).

**Comment by hjoliver** [comment]
You're welcome to do it (I just assigned you :-).  I think the documentation can be quite brief: just state that `results` must be a flat dictionary with keys that are valid environment variable names.  No need to elucidate every potential key name that breaks that, just refer users to shell documentation.

**Comment by sadielbartholomew** [comment]
Thanks for clarifying, @hjoliver.

>  I think the documentation can be quite brief: just state that results must be a flat dictionary with keys that are valid environment variable names. No need to elucidate every potential key name that breaks that, just refer users to shell documentation.

Sure, don't worry I will make sure I to be concise (even if it's a struggle for me)! I was detailed here mainly to outline my investigation method to anyone time in case they wanted to see/prove this for themselves.

I'll pop in a brief PR shortly.
