### ISSUE TITLE
Proposed changes to » Cylc 8 Migration Guide » Quick Summary Of Changes

### ISSUE THREAD

**Issue by datamel** [cylc/cylc-doc#413]
Proposed changes to » Cylc 8 Migration Guide » Quick Summary Of Changes, following documentation review discussion at MO team meeting.

Overall thoughts were that this section needs to have its content reduced to ensure it is a quick summary, with signpost links on where to get more information.

**Terminology** 
Fine, no changes proposed.
**Compatibility mode** 
Remove warning, too much info.
**Upgrading to Cylc8**
List of instructions that we recommend. 
Recommend validate, fix deprecations. Apply any breaking changes. Major changes section should have example of a suite needing upgrading. 
**Architecture** 
Too much here. Move this section to user guide. Just have a link for general architecture.
**New Web and terminal UI**
Just list the two commands with a link to more info.
**Scheduling Algorithm** 
Move to major changes section. Replace this with link – there is a new scheduling algorithm.
Include a highlight the differences in the old and new. Ensure changes are well documented, eg. Optional outputs, Reflow.  
**Task/Job States.** 
Text needs condensing. Although Task states need highlighting here. Pad it out and move to major changes, provide a link. Move to higher up in the document.
**Optional and expected task outputs.**
Needs cutting down, refer to major changes. Highlight suicide triggers/ Family trigger (finish?) and optional outputs.
Maybe a clear diagram rather than so much text.
This will need detailed section, covered in upgrading a graph. Will need good example as migration guide should cover the upgrade, user guide will only document new way of doing things.
**Window on the Workflow**
Abstract detail which does not belong here. Move to gui section. Should be something along the lines of "The gui uses this model, here is more detail for those who are interested". 
**Platform Awareness**
Replace with just a diff of workflow converted from host to platform. Link to rest of it in major changes. Users only need to know configuration change. Warning also needs moving.
**Graph Syntax**
Replace with there have been lots of config changes and link to major changes but this does not fit, the recommended validate and fix will be sufficient. This is covered by the upgrading to cylc-8. 
**Cylc Install**
Too long example. Replace with just a cylc install, cylc play example and say it replaces rose suite-run for rose users. Put link for more detailed example. 
**File Installation**
Fine
Move install files at startup link to user guide
**Symlink Dirs**
Fine
**Safe Run Semantics**
Change to Restart Behaviour. Trim to just play, pause…
**Security** 
Move away from here into user guide. Multi user should be in user guide, Security should be with architecture.
**Packaging** 
Remove, does not belong. 
**Task Job Scripts, Time Zones, Runahead Limit & Queues**
Move these to a combined bullet list section on other minor changes in behaviour, with runahead limits and queues, time zones.

**Comment by datamel** [comment]
Today UK side we have had initial discussions about what can be done to ease transition for users when working through the migration process - including tweaking the documentation. This issue is the outcome of the first discussion, which was limited to the Quick Summary of Changes section.
The overall feeling was that Quick Summary of Changes, has become a little bloated (with some great content that belongs elsewhere) and should be more concise.
Does this all sound reasonable @hjoliver? I don't think there is anything controversial here, mainly trying to condense the information so that users are less tempted to skip/skim and to point users to more detail in the Major Changes and the User Guide where appropriate.
The intention is that more reviewing of the documentation will take place after this initial pr.

**Comment by hjoliver** [comment]
> The overall feeling was that Quick Summary of Changes, has become a little bloated (with some great content that belongs elsewhere) and should be more concise.
> Does this all sound reasonable @hjoliver? 

Absolutely. As I commented in Element chat the other day, I initially wrote the the "Quick Summary" to help beta users before we had down the full doc upgrade.  Now that we have done a decent job of updating the bulk of the documentation, we can definitely slim down the summary.

**Comment by hjoliver** [comment]
I'll just query a few of the specifics:

> **Compatibility mode**
Remove warning, too much info. 

Which warning? There are four of them, all essential - are you suggesting reducing this to "there is a back-compat mode for `suite.rc` files, but there are some  [LINK TO] caveats"?  I guess that would be OK.

> **Task/Job States**.
Text needs condensing. Although Task states need highlighting here. Pad it out and move to major changes, provide a link

The first paragraph is unnecessary here, but we should have something like it somewhere early in the user guide. I don't think we every explained exactly what a "task" and a "job" are, previously.

> **Optional and expected task outputs.**
Needs cutting down, refer to major changes.
... Maybe a clear diagram rather than so much text.

Just to note, there are only 4 concise, separate, sentences in this section; it's not exactly verbose!  Fine to move it to major changes though.

> **Packaging**
Remove, does not belong.
 
Not sure I agree with this. Some users do install Cylc themselves, and this is a significant change, from downloading a release tarball and installing all dependencies yourself.  I can't see why a summary of changes should not include this.

Otherwise all good!

**Comment by hjoliver** [comment]
Section names should probably be changed to something like:

1. Summary of Major Changes
2. Detailed Description of Major Changes

**Comment by datamel** [comment]
Thanks for comments @hjoliver. 

> I'll just query a few of the specifics:
> 
> > **Compatibility mode**
> > Remove warning, too much info.
> 
> Which warning? There are four of them, all essential - are you suggesting reducing this to "there is a back-compat mode for `suite.rc` files, but there are some [LINK TO] caveats"? I guess that would be OK.

I have done this, linked to caveats in attempt to reduce the length of the entire document. 

> 
> > **Task/Job States**.
> > Text needs condensing. Although Task states need highlighting here. Pad it out and move to major changes, provide a link
> 
> The first paragraph is unnecessary here, but we should have something like it somewhere early in the user guide. Not sure we ever explained exactly the meaning of "task" and "job", previously.

I agree that they are important to explain here, I have left the definitions of task and job in. 

> 
> > **Optional and expected task outputs.**
> > Needs cutting down, refer to major changes.
> > ... Maybe a clear diagram rather than so much text.
> 
> Just to note, there are only 4 concise, separate, sentences in this section; it's not exactly verbose! Fine to move it to major changes though.

Again I have largely left this alone, slightly condensed it, there were links to more detail anyway.

> 
> > **Packaging**
> > Remove, does not belong.
> 
> Not sure I agree with this. Some users do install Cylc themselves, and this is a significant change, from downloading a release tarball and installing all dependencies yourself. I can't see why a summary of changes should not include this.

I have put packaging reference in the bullet list at the bottom to ensure it is documented here for users.

I will tag you as a reviewer, so you can let me know if you have any preferences for changes. No pressure to review it all, just as time permits.
