### ISSUE TITLE
Add 7.x and 8.x version symlinks to build?

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-doc#424]
We use symlinks in the build process to allow navigation to https://cylc.github.io/cylc-doc/latest and https://cylc.github.io/cylc-doc/stable. Currently these links are `latest -> 8.0rc1` and `stable -> 7.9.3`.

But when Cylc 8.0.0 is released, we'll want `stable -> 8.0.0`. So, to maintain easy access to the latest Cylc 7 docs, we should consider adding new symlinks `8.x` and `7.x`.

---

Note however that the latest Cylc 7 version is actually 7.9.6 - we haven't deployed docs for the last few maintenance releases either because we forgot or nothing has changed in the docs.

**Comment by oliver-sanders** [comment]
I think it's easy enough for users to select the relevant Cylc 7 version from the sidebar (we only have two versions, one for py26 the other for py27). Adding a further 7.x link (pointing at the py27 version?) is probably going to be more confusing than beneficial.

> either because we forgot or nothing has changed in the docs.

Shouldn't be any significant changes, the recent changes were largely Cylc 8 compat.
