### ISSUE TITLE
installation: document wrapper scripts for rose and isodatetime

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-doc#429]
We document the wrapper script for Cylc, but not for Rose, Rosie & Isodatetime.

https://cylc.github.io/cylc-doc/nightly/html/installation.html#managing-environments

There is some info in the wrapper script itself, however, being in the wrapper script it's not so prominent.

**Comment by wxtim** [comment]
@oliver-sanders: what is your target audience for this document?

**Comment by oliver-sanders** [comment]
> for this document?

I am not proposing a document but "people who are installing Cylc across a network".

**Comment by oliver-sanders** [comment]
Just need to go through the installation docs and find where it talks about the Cylc wrapper script and ensure that it recommends adding a similar wrapper for isodatetime (and rose as appropriate).
