### ISSUE TITLE
Installation: document pip extras

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-doc#430]
https://cylc.github.io/cylc-doc/latest/html/installation.html is missing information on the optional dependencies, e.g. the `[hub]` dependencies for `cylc-uiserver`. As per https://github.com/cylc/cylc-flow/pull/4745 perhaps it would be useful to be able to link to this info, e.g. `pip install cylc-uiserver[hub]`.

**Comment by MetRonnie** [comment]
We should probably link to that from the installation page?

**Comment by oliver-sanders** [comment]
We do https://cylc.github.io/cylc-doc/latest/html/installation.html#advanced-installation
