### ISSUE TITLE
drop numbered figures

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-doc#44]
Remove the figure numbering inherited from the LaTeX docs.

See "code block labels" comment in https://github.com/cylc/cylc-doc/pull/38#pullrequestreview-267514649 and the related #15

**Comment by sadielbartholomew** [comment]
#15 is unrelated.

**Comment by oliver-sanders** [comment]
> It turns out #15 is unrelated

This issue is about the `numfig` config not the `caption` option to the `code-block` directive.

**Comment by sadielbartholomew** [comment]
> This issue is about the numfig config

There is no ``numfig`` config now, it was there originally but has all been removed...

**Comment by oliver-sanders** [comment]
> There is no numfig config now, it was there originally but has all been removed

https://github.com/cylc/cylc-doc/blob/e6687ad413d3e6dfac637d0e1fd6f8d140a48fca/src/conf.py#L98-L100

**Comment by sadielbartholomew** [comment]
Fair enough, it must have been added in somewhere, I will amend the PR to remove that aspect. An explicit reference to the ``numfig`` aspect in this Issue would have helped to clarify.

**Comment by oliver-sanders** [comment]
> Fair enough, it must have been added in somewhere

It dates back to when the docs were in Cylc Flow:

https://github.com/cylc/cylc-flow/commit/1680de8204#diff-4460de81b835f04e942e1bc0ea016aacR59

**Comment by sadielbartholomew** [comment]
It really is not worth dwelling on why the setting to number figures are still there. I am removing the numbered figures, along with the numbered listings, as part of my PR.
