### ISSUE TITLE
Improve docs for truncated datetimes

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-doc#455]
There is currently no proper explanation of truncated datetime syntax

https://github.com/cylc/cylc-doc/blob/9304c0837d75bfcfcd6e0b09bc0a52f12c9f0920/src/user-guide/writing-workflows/scheduling.rst#L571-L591

**Comment by wxtim** [comment]
Can you give me some examples of what you mean by truncated datetime?

**Comment by MetRonnie** [comment]
I've updated the post

**Comment by wxtim** [comment]
@MetRonnie - Would a link to https://cylc.github.io/cylc-doc/stable/html/tutorial/scheduling/datetime-cycling.html#inferred-recurrence do you? Or do you think that we need to expand that?

**Comment by oliver-sanders** [comment]
Closed by #564
