### ISSUE TITLE
Repeated EMPY_BLOCK_REGEX in cylc_lang.py

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-doc#46]
Was looking at `cylc_lang` for #43, and noticed two `EMPY_BLOCK_REGEX` declarations. The second one replacing the first one:

![image](https://user-images.githubusercontent.com/304786/62085276-4baa8c80-b2af-11e9-97ec-60ca41b70199.png)

Just wondering if it's safe to remove the first one, or if it was intended to replace the second... I think @oliver-sanders or @sadielbartholomew might know?

**Comment by oliver-sanders** [comment]
Whoops, the first one can be deleted!

**Comment by kinow** [comment]
Ah, thanks for confirming! I'm trying to cure from an annoying cold (only running nose + sneezing), so went to bed earlier and am only read/approving things on GitHub. Will prepare a small PR for this one tomorrow, but happy if anyone beats me to it :+1:
