### ISSUE TITLE
Docs bug, env variable CYLC_WORKFLOW_SHARE_PATH does not exist

### ISSUE THREAD

**Issue by ashleysommer** [cylc/cylc-doc#465]
In the `general-principles.rst` file, it mentions the `share` dir is exposed in environment variable called `CYLC_WORKFLOW_SHARE_PATH` however this variable doesn't exist, I believe this section of the docs should use `CYLC_WORKFLOW_SHARE_DIR` or perhaps `CYLC_SUITE_SHARE_PATH`, I don't know which is more correct.

**Comment by oliver-sanders** [comment]
Thanks for reporting, yes that should be `CYLC_WORKFLOW_SHARE_DIR`.
