### ISSUE TITLE
"run hosts" doc: user host must see cylc-run too

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-doc#469]
Not clear from current docs.

 https://cylc.discourse.group/t/use-of-run-hosts/484

**Comment by wxtim** [comment]
I think that

> Share a common `$HOME` directory
 
is equivalent to saying yes to

>  Is it expected that the `[run host]` should share a disk with where you’re running `cylc play` ?

I'm going to make a suggestion on the docs, but I don't think there's a huge amount of change needed.
