### ISSUE TITLE
Check Tutorials

### ISSUE THREAD

**Issue by wxtim** [cylc/cylc-doc#470]
Some issues which came up looking at the tutorials recently.

1. Tutorials (in the `cylc-flow` repo) are tested with `.validate` files which contain scripts. We should check that these scripts match what the tutorials ask users to do:
  - It might be nice to have a (hidden) diff file so that the test can apply changes the learner needs to make and check that they make the workflow run/validate/whatever the tutorial says it should do. 
  - It would be good to have some checking mechanism to ensure that the tutorial and the `.validate` file can't get out of sync. One possibility might be to add an rst comment to the tutorials which can be sedded out and used to build the `.validate` file.
2. It's possible that the tutorials may use `cylc get-resources` command inconsistently: The [first tutorial](https://cylc.github.io/cylc-doc/nightly/html/tutorial/runtime/introduction.html#admonition-7) uses `cylc get-resources tutorial` (it won't work if you do `cylc get-resources tutorial/runtime-introduction` because the tutorial relies on files symlinked to cylc-forecasting-workflow), whilst [this practical](https://cylc.github.io/cylc-doc/nightly/html/tutorial/runtime/introduction.html#admonition-7) uses `cylc get-resources tutorial/runtime-tutorial`.

**Comment by oliver-sanders** [comment]
(I think manually checking the tutorials are still functional / valid is an 8.0.0 priority, checking automatically is another kettle of fish)

**Comment by wxtim** [comment]
> (I think manually checking the tutorials are still functional / valid is an 8.0.0 priority, checking automatically is another kettle of fish)

That's what I mean, I've been through them, automation can been pushed till later.

**Comment by oliver-sanders** [comment]
Then we can close this?

**Comment by wxtim** [comment]
> Then we can close this?

Once #4989 is in or I'm told it's unnecessary.

**Comment by wxtim** [comment]
> Then we can close this?
