### ISSUE TITLE
excessive escape characters in doco

### ISSUE THREAD

**Issue by ColemanTom** [cylc/cylc-doc#5]
I was looking for something in the doco and noticed, what I believe are a lot of unintentional `\` characters. For example, in https://cylc.github.io/doc/built-sphinx-single/index.html#scheduling-xtriggers-many

`Replace \_\_MANY\_\_ with any user-defined event trigger` I assume is meant to be `Replace __MANY__ with any user-defined event trigger`? I just wanted to check just in case it is intended.

![image](https://user-images.githubusercontent.com/15375218/57416289-01cb8080-7243-11e9-97ef-9919004a44cf.png)

**Comment by oliver-sanders** [comment]
Closed by https://github.com/cylc/cylc-doc/pull/121
