### ISSUE TITLE
Better descriptions for task event handlers in reference

### ISSUE THREAD

**Issue by MetRonnie** [cylc/cylc-doc#505]
These descriptions need fleshing out.
> `flow.cylc[runtime][<namespace>][events]handlers`
> Type: `list`
> Specify a list of command lines or command line templates as task event handlers.

and e.g.
> `flow.cylc[runtime][<namespace>][events]submitted handlers`
> Type: `list`
> Handlers to run when this task is submitted.

It is unclear what you can write for these settings. Examples should be given.

**Comment by wxtim** [comment]
@MetRonnie would a link to https://cylc.github.io/cylc-doc/8.0rc3/html/user-guide/writing-workflows/runtime.html#event-handling in each item be enough for you? I think it answers your questions.

**Comment by MetRonnie** [comment]
Yes it should link to the user guide. I also think "an event handler is a script which can be stored in `bin/`" would be a useful thing to mention.

**Comment by wxtim** [comment]
I think that the top level description on the events section https://cylc.github.io/cylc-doc/nightly/html/reference/config/workflow.html#flow.cylc[runtime][%3Cnamespace%3E][events] Is enough IMO.

**Comment by wxtim** [comment]
Closed by https://github.com/cylc/cylc-flow/pull/5212
