### ISSUE TITLE
Spell check follow-up

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-doc#515]
- Address "Follow up questions" listed here: https://github.com/cylc/cylc-doc/pull/501#issue-1313471914
- Eliminate US spellings from the new dictionary listing (and from the docs)

Vote on the following: add :+1:  to preferred choice:
- parametrize 
- parameterize   :+1: :+1:
- parameterise   :+1:

**Comment by MetRonnie** [comment]
[According to Google ngram viewer for British English](https://books.google.com/ngrams/graph?content=parametrize%2Cparameterize%2Cparametrise%2Cparameterise&year_start=1800&year_end=2019&corpus=29&smoothing=3&direct_url=t1%3B%2Cparametrize%3B%2Cc0%3B.t1%3B%2Cparameterize%3B%2Cc0%3B.t1%3B%2Cparametrise%3B%2Cc0%3B.t1%3B%2Cparameterise%3B%2Cc0)

![image](https://user-images.githubusercontent.com/61982285/184324536-e3f5b637-120b-44c7-af50-b7d1f993c180.png)

**Comment by hjoliver** [comment]
Damn, parameters really took off in the late '60s.

I'm fine with "parameterize" - but is the 'z' not US in this case?   I don't like "parametri(sz)e" (missing 'e' in the middle).

**Comment by MetRonnie** [comment]
It's apparently popular to spell with a "z" in British English. IDK, looking at my MSc project I used "parametrise" actually (I remember deciding on that spelling for a reason, but can't remember what that reason was!)

**Comment by oliver-sanders** [comment]
I think the spellcheck has broken `make watch` which is now stuck in an infinite rebuild loop due to this:

```
[sphinx-autobuild] Detected change: /net/home/h06/osanders/cylc-doc/src/dictionaries/words
```

There are also a bunch of warnings to fix:

```
direct use of the spelling directive is deprecated, replace ".. spelling::" with ".. spelling:word-list::"
Extending local dictionary for reference/config/writing-platform-configs with ['clusterA', 'clusterB']
reference/config/writing-platform-configs ['clusterA', 'clusterB']
direct use of the spelling directive is deprecated, replace ".. spelling::" with ".. spelling:word-list::"
Extending local dictionary for tutorial/runtime/runtime-configuration with ['exeter']
tutorial/runtime/runtime-configuration ['exeter']
direct use of the spelling directive is deprecated, replace ".. spelling::" with ".. spelling:word-list::"
Extending local dictionary for user-guide/sharing-access-to-workflows with ['userA', 'userB']
user-guide/sharing-access-to-workflows ['userA', 'userB']
```
