### ISSUE TITLE
Demote forecasting context from very first UG section

### ISSUE THREAD

**Issue by sadielbartholomew** [cylc/cylc-doc#54]
Currently the User Guide opens with two items, 'Scheduling Forecast Suites' & 'EcoConnect', which chronicle in detailed paragraphs the NWP origins & background to Cylc.

While those sections are useful, having them as the very first sections could put off potential users who are considering Cylc for other contexts. It would be more appropriate to instead have the leading content concisely & directly summarise what Cylc is, or how to (install &) get started using it, as those are the most likely questions users will have when they consult the documentation.

**Comment by oliver-sanders** [comment]
Done, can't remember when but done :)
