### ISSUE TITLE
Document how to manage task re-run by insertion

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-doc#56]
To re-run tasks that already ran, users need understand the following:
- for a single task still in the task pool, just re-trigger it
- for multiple inter-dependent tasks still in the task pool, manually reset them to waiting in upstream-first order
  - (in the other order they'll each just retrigger immediately, off of the old upstream task states)
  - (to stop the most-upstream one triggering immediately - if its prerequisites are already satisfied - reset its upstream dependants to failed then reset it to waiting; or just hold the suite).
- tasks that have already disappeared from the task pool have to be re-inserted in order to re-run them
- re-inserted tasks will trigger immediately if their dependencies can be satisfied by the current task pool
  - (unless the suite is held) 

Also:
- to re-insert and run tasks that were removed from the task pool by suicide triggers, you have to manipulate upstream state so that the suicide triggers are no longer satsified on insertion (else they'll just suicide again immediately) - https://github.com/cylc/cylc-flow/issues/3282#issuecomment-520623763

**Comment by oliver-sanders** [comment]
@hjoliver good to close post SoD?

**Comment by hjoliver** [comment]
Yep, good spotting.  No longer relevant.
