### ISSUE TITLE
Add troubleshooting to documentation

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-doc#6]
Being the one with less experience on troubleshooting Cylc, it has always been challenging when a cylc workflow did not behave the way I expected it to.

Other tools include sections with tips for admins and developers to troubleshoot the tools. Maybe we could do the same? Here are some cases that could be documented (feel free to edit this or add more comments):

- [ ] troubleshoot problems building the project with `pip`, `virtualenv`, `conda`, etc. e.g. if you have a `build` directory from a previous `python setup.py bdist` it may interfere when using virtual environments

**Comment by hjoliver** [comment]
(We should try to prioritize this!)

**Comment by oliver-sanders** [comment]
Closed by #638
