### ISSUE TITLE
Inconsistant documentation of UTC mode

### ISSUE THREAD

**Issue by jfrost-mo** [cylc/cylc-doc#601]
UTC mode is described as having an effect on datetime cycling in [some parts](https://cylc.github.io/cylc-doc/stable/html/workflow-design-guide/general-principles.html#utc-mode) of [the docs](https://cylc.github.io/cylc-doc/stable/html/tutorial/scheduling/datetime-cycling.html#utc-mode) while the [config reference](https://cylc.github.io/cylc-doc/stable/html/reference/config/workflow.html#flow.cylc[scheduler]UTC%20mode) says it only affects log timestamps.

In addition with the [cycle point time zone](https://cylc.github.io/cylc-doc/stable/html/reference/config/workflow.html#flow.cylc[scheduler]cycle%20point%20time%20zone) now defaulting to UTC the advice about explicitly setting UTC mode are probably not needed any more.

**Comment by MetRonnie** [comment]
The workflow config reference is correct. These two are out of date:
https://github.com/cylc/cylc-doc/blob/84bb4b555e86a40cd398ed0215e5a3352bc0b183/src/workflow-design-guide/general-principles.rst?plain=1#L11-L22
https://github.com/cylc/cylc-doc/blob/84bb4b555e86a40cd398ed0215e5a3352bc0b183/src/tutorial/scheduling/datetime-cycling.rst?plain=1#L271-L283
