### ISSUE TITLE
changelog: 8.2.0

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-doc#621]
Update the changelog for release.

https://github.com/cylc/cylc-doc/pull/620/files#diff-5e32020ee8ca62dbbb32fa32a90cd6e4a0d08691f3b1c61550459564b4c0a066R31

**Comment by wxtim** [comment]
@oliver-sanders  - you want me to look for any other changes required or confirm that I've looked, don't think they are required and close the issue?

**Comment by oliver-sanders** [comment]
Skim the changelogs and make sure that every substantial user-facing feature is represented.

**Comment by wxtim** [comment]
The only things that I think _might_ be worth adding are 

- Restoration of `-n` in VIP 5227
- Restart with timeout 5231
- You can now run Cylc VR from Cylc TUI!  5381 
- `-z` 5433 (unless we are keeping that under our hat)

Items 1, 3 and 4 could be a single section called something like `CLI & TUI` and given one bullet point each.

@oliver-sanders  what do you think?

**Comment by oliver-sanders** [comment]
Nah, nothing worth adding.
