### ISSUE TITLE
8.3.0 changes

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-doc#633]
(attempt after Cylc component releases)

Before releasing the 8.3.0 docs check src/references/changes.rst

* Ensure major user-facing changes are documented.
* Uncomment the "Cylc Components" box and ensure the links work.

**Comment by wxtim** [comment]
Have locally merged all outstanding branches into my master copies, and built the docs with no errors. Served locally at `${MYSERVER}/cylc-doc/8.3.0.dev/html/index.html`

**Comment by oliver-sanders** [comment]
Off topic?

**Comment by wxtim** [comment]
> Off topic?

Intended to be a compiled set of docs to check the changes against.

**Comment by wxtim** [comment]
Done checks.

**Comment by oliver-sanders** [comment]
I think we might be missing some changes entries, e.g. the new gantt view?

**Comment by wxtim** [comment]
Feature not to changes.rst (that you might disagree on)
* Simulation mode broadcastable (not of huge interest)
* Xtriggers via entry point (not sure that we want to advertise yet?) https://github.com/cylc/cylc-flow/blob/master/changes.d/5831.feat.md
* Cylc lint #NoQa -- too small a change

**Comment by oliver-sanders** [comment]
Yep, all rather small, don't need advertising here.
