### ISSUE TITLE
Clarfiy Python version range required for custom xtriggers

### ISSUE THREAD

**Issue by sadielbartholomew** [cylc/cylc-doc#66]
We currently do not specify any information about the necessary Python version that custom xtrigger functions can be written in, just that e.g. "Trigger functions are just normal Python functions".

From a quick test, in ``8.0a0``, an xtrigger written with Python 3 print function syntax works as it should, but if instead changed to Python 2 print statements, it throws a ``SyntaxError: Missing parentheses in call to 'print'.``

From this & then going on to check in the ``cylc-flow`` codebase, it seems that xtriggers must more specifically be compatible with the [version of Python required by ``cylc-flow``, namely ``>=3.7``](https://github.com/cylc/cylc-flow/blob/283bda1da40ee0d3baa14556000f4d6a4e3f4d43/setup.cfg#L48).

A few questions, perhaps for @hjoliver or @kinow (but if anyone else wants to respond that is fine), before I add in this information:

* Can you confirm, to double check, that the Python versions xtriggers must be written in to work properly is the same as the range of Python versions for ``cylc-flow``?
* For the docs, do we feel it is necessary to detail the minor version, or is it sufficient to state that xtriggers must be written in *Python 3*? I ask since xtriggers are usually quite simple, so it may be overkill to provide a  more precise range?

**Comment by kinow** [comment]
It should match the minimum version of Python from Cylc Flow, to avoid runtime errors. We could leave Py3 in setup.py if that's easier to maintain, but we would still need to inform users about risks of using functions ot syntax not supported in Cylc Flow's version of Python.

**Comment by hjoliver** [comment]
Xtrigger functions are minimally wrapped to create a Python program, with `bin/cylc-function-run` which has the same `#!/usr/bin/env python3` as all the Cylc commands.  So the definitive answer is: **custom xtrigger functions must be compatible with the same Python version that runs the Cylc workflow server program.**.

**Comment by hjoliver** [comment]
I think it is potentially misleading to say more than this, because it's **possible** (if unlikely) for a custom xtrigger function to use Python syntax that is not used anywhere in cylc-flow, in which case the xtrigger could be compatible with a different range of Python versions that cylc itself is - but that doesn't actually matter so long as it is compatible with the specific Python version being used.

**Comment by hjoliver** [comment]
(And Python does occasionally make breaking changes between versions).

**Comment by sadielbartholomew** [comment]
Excellent, thanks @hjoliver. It seems natural to address this Issue then by adding in the summary sentence you provided:

> custom xtrigger functions must be compatible with the same Python version that runs the Cylc workflow server program.

in the appropriate place, so that's what I will do, unless anyone puts further comments suggesting otherwise.
