### ISSUE TITLE
Document meaning of inactivity timeout

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-doc#684]
The inactivity timeout is not affected by the presence of unsatisfied xtriggers (including clock triggers), which might be surprising if you abort on inactivity timeout in a clock-triggered workflow.

It seems a bit aggressive to abort on "inactivity" if there are active tasks and/or active xtriggers present.

On the other hand, if we made it more friendly, it might just be equivalent to the stall timeout.

I think this feature was originally added primarily for use in functional tests, where we might assume something has gone wrong if nothing is happening, even if the workflow is not technically stalled.

At the very least, we should document for users exactly what "inactivity" means.

**Comment by oliver-sanders** [comment]
The existing docs are here:

https://cylc.github.io/cylc-doc/stable/html/user-guide/writing-workflows/scheduler.html#workflow-events
