### ISSUE TITLE
document: cylc set

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-doc#688]
The documentation side of https://github.com/cylc/cylc-flow/pull/5658

* [ ] Update any references to `cylc set-outputs`.
* [ ] Update any documentation about resetting tasks.
* [x] Document `cylc set` functionality as appropriate.
* [x] Add a "changes" entry for this breaking change.

**Comment by oliver-sanders** [comment]
Added changes entry in https://github.com/cylc/cylc-doc/pull/710

**Comment by oliver-sanders** [comment]
Added example interventions in https://github.com/cylc/cylc-doc/pull/723

**Comment by hjoliver** [comment]
Closed by #732
