### ISSUE TITLE
Convert to Cylc 8 terminology & clarify changes

### ISSUE THREAD

**Issue by sadielbartholomew** [cylc/cylc-doc#83]
There are a small number of key terms we have agreed to change for Cylc 8. We should  **convert the documentation to consistently use the new Cylc 8 terms**, for regularity & to get users familiar with the new terms, but also because otherwise new users who start off using version 8 without having ever used 7 (or earlier) could become confused.

Completing the changes themselves should be trivial by ``sed`` replacement, but care will be required to ensure that the conversions aren't being made in inappropriate instances (e.g. within ``suite.rc``, which will likely be going to some other name than ``workflow.rc``, e.g. ``cylc-flow.rc``, hence we should not touch ``suite.rc`` references.)

I also propose that we **create a dedicated docs section or item, e.g. a note directive at the top of the glossary page, to clarify the changes made from Cylc 7 to Cylc 8**, mainly to enumerate all of these for reference as a 7 to 8 transition aide, but also to add brief background on reasoning behind the changes, in case users were curious.

### Agreed terminology conversions

Main items (top two) are as lifted from [the 'Cylc-8 Architecture' document](https://cylc.github.io/cylc-admin/cylc-8-architecture#cylc-terminology) & are generally agreed. Please add other conversions if they seem appropriate.

| Old term, to convert *from* (Cylc 7)  | New term, to convert *to* (Cylc 8) | Approximate number instances of old term (:eight_pointed_black_star:) |
|---|---|---|
| suite | workflow | 1433 |
| suite server program (& before that 'suite daemon') [note changing the above first will convert the name intermediately to 'workflow server program' etc.] | workflow service  | 73 (0 now for 'suite daemon' :tada:) |

:eight_pointed_black_star:: from running ``git grep --count <old term> | awk 'BEGIN {cnt=0;FS=":"}; {cnt+=$2;}; END {print cnt;}'``, where we consider it approximate since it applies at time the command is run only.

### Completed terminology conversions

- [x] suite
- [x] suite server program

**Comment by oliver-sanders** [comment]
* Glossary added with new terminology defined (pending final re-review pre release).
* Cylc 7->8 migration guide started, terminology changes documented there.
* Suite, suite daemon and Suite server program terms eradicated.
* Remaining matters covered by final re-review and #170.
