### ISSUE TITLE
Document why task messages are not retried in Cylc 8

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-doc#87]
See https://github.com/cylc/cylc-flow/pull/3348#discussion_r332341533

**Comment by dpmatthews** [comment]
This is already documented in the release notes.
That seems sufficient to me.
@hjoliver - can we close this?

**Comment by hjoliver** [comment]
Hmm, I was thinking that's not sufficient because task message retries seem like the sort of thing users (or future Cylc developers) might expect to happen, in which case it would be helpful to explain why we don't do it, and avoid reimplementing it again some way down the track.

**Comment by hjoliver** [comment]
(PR posted to document the reason).

**Comment by dpmatthews** [comment]
Personally I don't think new users of Cylc would expect task message retries and information for future Cylc developers is better in the code that the user docs. No big deal though.

**Comment by dpmatthews** [comment]
... and I do think it's good to make it clear in the user guide how polling deals with any messaging failures
