### ISSUE TITLE
Publish Cylc 8 User Guide

### ISSUE THREAD

**Issue by hjoliver** [cylc/cylc-doc#90]
(Do we have this documented somewhere else?)

We are considering publishing the user guide for Cylc 8 to readthedocs and/or our own site.

However, for anyone trying Cylc 8 preview versions, it really needs to be available already.  So our own site will do, at least as an interim measure.

**Comment by kinow** [comment]
+1 for publishing it now, even if incomplete.

I think RTD supports multiple versions. So we could perhaps upload 7.8.4, and then 8.0a1 there as well, and let users choose.

Tornado (https://readthedocs.org/projects/tornado/) and requests (https://readthedocs.org/projects/requests/) publish multiple versions of their docs.

**Comment by oliver-sanders** [comment]
Published.
